apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    app: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: ulysysdev/payment:v1
          ports:
            - containerPort: 8080
          # env:
          #   - name: superuser.userId
          #     value: some_value					
          #   - name: _DATASOURCE_ADDRESS
          #     value: mysql
          #   - name: _DATASOURCE_TABLESPACE
          #     value: orderdb
          #   - name: _DATASOURCE_USERNAME
          #     value: root
          #   - name: _DATASOURCE_PASSWORD
          #     valueFrom:
          #       secretKeyRef:
          #         name: mysql-pass
          #         key: password
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5